### ISSUE TITLE
 Failed to load 'http://localhost:8080/pentaho/Xmla

### ISSUE THREAD

**Issue by marcushenningsen** [rpbouman/xmla4js#18]
I can't seem to get it to work. I have installed Pentaho BI Server 5.2 which works very well with e.g. Saiku. I can also access my cubes from MS Excel through the [XMLA connect](http://xmlaconnect.sourceforge.net/).

I have extracted the xmla4js zip file and can access the web page. However, when I turn to the samples and try to connect to my local pentaho server, I get the above error message. The same message turns up if I try to use credentials (http://localhost:8080/pentaho/Xmla?userid=admin&password=password).

I found this rather old forum post (http://forums.pentaho.com/showthread.php?73803-XMLA-Connection-from-SimbaO2X-Provider), however, the proposed solution doesn't change anything.

Is xmla4js tested against Pentaho 5.*? Or is the problem somehow related to my configuration (although it works from MS Excel through XMLA connect)?

Kind regards,
Marcus

**Comment by rpbouman** [comment]
@marcushenningsen, where did you get the xmla4js zip file? I don't believe the xma4js project on github has zips for distribution. 

To work with the xmla4js project (that is, play around with the samples, read the documentation, and perhaps contribute to xmla4js itself) the recommended installation path is to fork the xmla4js repo directly into {biserver-home}/pentaho-solutions/system. You'll then get a number of Xmla4js menu items in the tools menu. 

To use xmla4js in your own plugin, you don't need to fork the repo but you can simply download one of the minified js files from the js directory, or the Xmla4js source file from the src directory (for debugging purposes), and include them in your plugin or project just like any other javascript resource.

Xmla4js has been tested with 5.2. To make sure I just tried again, and it works for me. To be sure, what I did is: Menu: Tools > Xmla4js Home. Then, from the home page, follow the "Samples" link. Then, click the 2nd sample, "discover-synchronous.html". In the sample file the URL should be pre-set to "http://localhost:8080/pentaho/Xmla". Hitting the "Discover" button should then load an initial item in the treeview at the lower half of the page that you can browse. 

Before you check this, please be aware that there has been a recent change in Pentaho in how XML/A datasources are exposed. 

To check if XML/A is enabled for a particular data source, open the "manage datasources" dialog (menu: File > Manage Datasources)
In the dialog, click the datasource of the type "Analysis" that you want to use with xmla4js. Then, edit the datasource by choosing "Edit" form the popup menu beneath the gear icon immediately left of the "New Datasource" button. The edit dialog pops up. Select the "Manually enter data source parameter values" radio button, and set the EnableXmla property to true.

Let me know if this works. If you run into an error again, please open your browsers developer tools and look at the network requests done by xmla4js. Please include the request and the response so I can see what is going on.

**Comment by marcushenningsen** [comment]
@rpbouman, thanks for the reply.

The zip-file is available in the right side pane at the project's [front page](http://localhost:8080/pentaho/Xmla). There's a button saying "Download ZIP".

I suspected something was wrong with my installation, so I just downloaded all 5-versions of the server and tested the tool and it works fine in all of them except the brand new 5.3 where an error is thrown: "XMLA discover unparse result error"

I don't know what is wrong the initial installation, perhaps some conflict with another plugin. However, since it's working fine, I will go on with a fresh 5.2 installtion from here and try to embed it in a website. Thanks for the reply.

**Comment by rpbouman** [comment]
@marcushenningsen thanks for the quick reply! Glad it seems to work now. And thanks for telling me about the link. I'll remove it from the page.

I'll check out 5.3. 

For now I will close this issue since it seems the reported problem has gone away. Don't hesitate to re-open should you have information that the problem still persists.

kind regards,

Roland
