### ISSUE TITLE
Unescape character function does not return correct value

### ISSUE THREAD

**Issue by ajkaushik** [rpbouman/xmla4js#28]
If the data from OLAP source has & in it, SOAP message has it correctly as &amp; But rowset from xmla4js shows undefined in place of &. 
By looking at source code, the function for unescape characters, correctly identifies the value, but does not return it and hence end result has undefined.

**Comment by gh0st** [comment]
What line do you see this on @ajkaushik ?

**Comment by rpbouman** [comment]
I can't reproduce this. I have cubes with & in captions, and it works for me. Please provide me sample Xml/A response so I may test?

**Comment by gh0st** [comment]
It’s possible I could have figured this out. Probably safe to close this issue. 

Chad Hollman

**Comment by rpbouman** [comment]
Hi Chad! Thanks for the reply - much appreciated! I will close the issue, but feel free to re-open if it pops up.
