### ISSUE TITLE
Pass credentials with xmla request?

### ISSUE THREAD

**Issue by gh0st** [rpbouman/xmla4js#29]
Is there a way of passing windows credentials to the HTTP OLAP instance along with the xmla request?

**Comment by rpbouman** [comment]
Xmla4js uses whatever authorization scheme is in place for the service. 
Depending on what Xmla provider you are using, it may prompt you for credentials, or you might need to set specific headers. Some providers use basic authentication - In those cases, you can pass user and password.

In both cases, you can do this by setting them in the request object, or set it in the options using getOptions:

xmla.request({
  user: ..., password: .... //credentials for providers using basic auth
  ...,
  headers: { // some providers handle authorization through specific headers - you can set those too:
    headerName: headerValue,
    ...
  }
});

or 

xmla.setOptions({
  user: ..., password: .... //credentials for providers using basic auth
  ...,
  headers: { // some providers handle authorization through specific headers - you can set those too:
    headerName: headerValue,
    ...
  }
})
