### ISSUE TITLE
Example usage - how would a request to the example server look like?

### ISSUE THREAD

**Issue by shani117** [rpbouman/xmla4js#34]
Hi there,

I was trying to use this package in a server that I already have and use it to connect to a Azure PaaS SSAS offering. I was wondering how would a request look like for the example included in this project - https://github.com/rpbouman/xmla4js/blob/master/examples/example-xmla4js-nodejs-app.js? I understand that the server in the example is taking the incoming URL and building everything off of that. It would be great to see an example of what that request/incoming URL would look like or how should that be structured. Please advise.

Thanks,
Shani.

**Comment by rpbouman** [comment]
It has been a while so I maybe wrong but it would be something like:

GET http://<yourhost>/example-xmla4js-nodejs-app.js?url=<url of your XML/A service>

this would do a DISCOVER_DATASOURCES XML/A request and return the results (https://docs.microsoft.com/en-us/sql/analysis-services/schema-rowsets/xml/discover-datasources-rowset?view=sql-analysis-services-2017). Using the result of this response gives you the available catalogs, and possibly a new value for the url

GET http://<yourhost>/example-xmla4js-nodejs-app.js/<CATALOG_NAME>?url=<url of your XML/A service>

will do a DISCOVER request for MDSCHEMA_CUBES (https://docs.microsoft.com/en-us/sql/analysis-services/schema-rowsets/ole-db-olap/mdschema-cubes-rowset?view=sql-analysis-services-2017)

GET http://<yourhost>/example-xmla4js-nodejs-app.js/<CATALOG_NAME>/CUBE_NAME?url=<url of your XML/A service>

will do a DISCOVER request for the MDSCHEMA_DIMENSIONS in the specified cube (https://docs.microsoft.com/en-us/sql/analysis-services/schema-rowsets/ole-db-olap/mdschema-dimensions-rowset?view=sql-analysis-services-2017)

...and I think you'll get the picture now - adding more path elements will let you get hierarchies, levels, members and properties as well.

For executing MDX, you can do a request like this:

GET http://<yourhost>/example-xmla4js-nodejs-app.js/<CATALOG_NAME>?url=<url of your XML/A service>&mdx=<Your MDX Query>

Valid content types for the response are:

"text/csv","text/plain" for CSV output,
"text/html", "application/xhtml+xml" for (X)HTML output.
"text/xml", "application/xml" for XML output (pass through XML received from the provider)
"text/json", "application/json" ,
            "text/javascript": toJavaScript,
            "application/javascript": toJavaScript

You can pass these either through the Accept request Header, or as the "format" parameter in the query, like so:

GET http://<yourhost>/example-xmla4js-nodejs-app.js?url=<url of your XML/A service>&format=<content-type>

(Specifying format as query option will override the Accept header)

**Comment by rpbouman** [comment]
BTW nobody is actively updating the npm package. It was created at a time when someone convinced me node was all the shit and I should package for that. So I did but I never got any signals people were actually using it. So, please let me know if you are interested in an updated package for node, or otherwise, just grab the latest version and import it yourself in your node project.

**Comment by shani117** [comment]
Thanks for your updates Ronald. Much appreciated. I'll try the URL formats you suggested. I was planning on leveraging this package directly in another NodeJS server from where I will be calling the XMLA service exposed by Azure SSAS service. As such, the calls will not be URL based. I'll have to build the requests, set necessary headers (auth tokens at the very least) and then execute some DAX/MDX queries against the cubes.

If you do have any updated Node packages, please do share. I'm using the currently published package for now (version 0.0.2).

Thanks again for your response.
Shani.

**Comment by rpbouman** [comment]
@shani117, my suggestion is that you don't use the published node package, but grab either the Xmla.js from src or the compiled or minified one from the js directory. Xmla4js is arm compliant so it should not be any issue to require it in your node script. 

The "URL-based calls" are only an illustration for the node js example. They are not indicative of any kind of real-world solution - it is merely a sample to illustrate use in node. 

For the regular api, just checkout the doc/api docs, that's what they are there for. The browserbased samples also illustrate the use of the actual API.
